<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
    <joint name="camera_joint" type="fixed">
        <parent link="chassis"/>
        <child link="camera_link"/>
        <origin xyz="${box_x/2+lidar_length*0.7/2} 0 0" rpy="0 0 0"/>
    </joint>
    
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${lidar_length*0.7} 0.03 0.03"/>
            </geometry>
            <material name="pink"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
        <inertial>
            <mass value="0.1" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
                     iyy="0.0001" iyz="0.0" 
                     izz="0.0001" />
        </inertial>
        
    </link>


     <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>


    <link name="camera_link_optical">
    </link>




<gazebo reference="camera_link">
    <sensor name="camera" type="camera"> 
        <pose> 0 0 0 0 0 0 </pose>
        <visualize>true</visualize>
        <always_on>true</always_on>
        <update_rate>10</update_rate>
        <topic>camera/image_raw</topic> 
        <gz_frame_id>camera_link_optical</gz_frame_id>
        <camera>
            <horizontal_fov>1.089</horizontal_fov>
            <image>
                <format>R8G8B8</format>
                <width>320</width>
                <height>240</height>
            </image>
            <clip>
                <near>0.05</near>
                <far>8.0</far>
            </clip>
            <camera_info_topic>camera/camera_info</camera_info_topic>
        </camera>
        <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
            <render_engine>ogre2</render_engine>
            <frame_name>camera_link</frame_name>
        </plugin>
    </sensor>
</gazebo>

</robot>