<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    


    <xacro:property name="imu_x" value="0.03"/>
    <xacro:property name="imu_y" value="0.03"/>
    <xacro:property name="imu_z" value="0.01"/>

    <joint name="imu_joint" type="fixed">
        <parent link="chassis"/>
        <child link="imu_link"/>
        <origin xyz="${-box_x/2+wheel_radius} 0 ${box_z/2 + imu_z/2}" rpy="0 0 0"/>0
    </joint>
    
    <link name="imu_link">
        <visual>
            <geometry>
                <box size="${imu_x} ${imu_y} ${imu_z}"/>
            </geometry>
            <material name="blue"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
        <inertial>
            <mass value="0.1" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
                     iyy="0.0001" iyz="0.0" 
                     izz="0.0001" />
        </inertial>
        
    </link>




<gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
        <always_on>1</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <topic>imu</topic>
        </sensor>
</gazebo>

</robot>